---
abstract: 'Toolkit for CLI Automation'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200013, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-CLI-Interact
requires:
  Class::MOP: 0
  Class::MOP::Class: 0
  File::Basename: 0
  FileHandle: 0
  IO::Pty: 0
  IPC::Run: 0
  List::Util: 0
  Log::Dispatch::Config: 0
  Log::Dispatch::Configurator::Any: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  Net::Telnet: 0
  POSIX: 0
  Path::Class: 0
  Time::HiRes: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-CLI-Interact
  homepage: https://github.com/ollyg/Net-CLI-Interact/wiki
  repository: git://github.com/ollyg/Net-CLI-Interact.git
version: 1.120042
