---
abstract: 'Toolkit for CLI Automation'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  Test::More: 0.88
  warnings: 0
configure_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-CLI-Interact
no_index:
  directory:
    - t
    - inc
requires:
  Class::Load: 0
  Class::Mix: 0
  File::Basename: 0
  FileHandle: 0
  IO::Pty: 0
  IPC::Run: 0
  List::Util: 0
  Log::Dispatch::Config: 0
  Log::Dispatch::Configurator::Any: 0
  Moo: 0
  Moo::Role: 0
  MooX::Types::MooseLike::Base: 0
  Net::Telnet: 0
  POSIX: 0
  Path::Class: 0
  Sub::Quote: 0
  Time::HiRes: 0
  strict: 0
version: 2.200000
